language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
before_install: if [[ `npm -v` < 2 ]]; then npm i -g npm@latest-2; fi
install: npm install --no-optional
script: npm test
deploy:
  provider: npm
  email: axel.eirola@iki.fi
  api_key:
    secure: T9ZpeB3gEqFeitlis8wxIyGwbLiOq7ykgZzY9PRSHy++/YyinaF3p3jrgQVyRtgaN/6kUiGitsviNx0/gvTkI/plmX/4F2jpTaPrR9bfPPFOX62t+5346NsYyA0Ip+kYafdim5+RkLLEQlYCpRC1IscOW9I0r8OC6xnjhK/cN+K6p1k9uzvqH979jeGwmAqhxYY5KL/OLNTR3ri3RYQ3xyVUJM0VCYwEhxjKXJxGX5cC7AeXVU0X4HIHah+89M7jc8BzhoBMm2ZUyG8IwccKf2ag9dFzcVs4NeD4U6vyL2Y3YztWeuG7DIf4Y626RC/AYpZi14yYD7LBila5WX885dw7Mpz6yg/NoOW/g2TIN7rRjM34qaCw3dX2WMmr+jIoder5i5CL+IL9pin28NSXp8PZUMHz5KiVk9+LKZeeD7EbxTOCvq0q1uYsTgKLWcu5Hw0USvkAc4CWSGuM1S4Ze/5DrD5OIs7MrsrL3beHDHjYvF6ORA1YxneD0h3LYmgiEHlzTmiwKngGQew8NYaPMeBNoildNE1AhInMzEQY4AaI3yJ43pTL8hVx++U8JxeOGECPciSPHFuVKlfMgdEX1YGbq/SHR0U42dYgpyrVOb+4gyvOYEtKuRj3zDTRWqd14mEVvTLzg1NQXbQSPX47W6mvJnu4LFtjAhmKwae8Gzc=
  on:
    tags: true
    repo: aeirola/slack-irc-client
